[package]
name = "machina"
version = "0.3.0"
authors = ["ion <ionix@protonmail.com>"]
repository = "https://github.com/ioncodes/machina"

[dependencies]
libc = "*"
aligned_alloc = "*"
region = "*"

[dev-dependencies]
sam = "0.2.0"
